# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Xinyao (Cynthia) Zhang
title: Open to work
email: xinyaozhang@ufl.edu
# website: https://xinyao-zhang.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: XinyaoZhang14
googlescholar_username: TdLKY9UAAAAJ&hl
linkedin_username: xinyaocynthiazhang
github_username:  Xinyao-Zhang
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# orcid_username: 0000-0003-4655-7050

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | 
  Hey! I am a Ph.D. candidate at the University of Florida, mentored by Dr. Sara Behdad. 
  My research leverages <b>machine learning</b> to enhance safety and efficiency in manufacturing environments, with a focus on <b>human-robot collaboration</b>.

  Alongside my doctoral research, I've pursued a specialization in signals and systems as part of the ECE master's program at UF. I've developed expertise in constructing machine learning models using TensorFlow and PyTorch in Python.
  
  I am passionate about translating theoretical knowledge into practical solutions that drive innovation and enhance productivity in the manufacturing sector!

  Research interests: <p style="color:#ff69b4;">Research interests</p>
    - <mark>Human intent and activity recognition</mark>
    - <mark>Early prediction</mark>
    - <mark>Self-supervised learning</mark>

# <em>Please find my complete Curriculum Vitae (CV) here: <a href="https://github.com/AminSahebi/resume/tree/main/data/resume_Amin_Sahebi.pdf" download="SAHEBI_CV.pdf"><mark>Download</mark></a></em>
#   - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Projects 
    layout: list 
    content:
      - layout: top-middle
        border: weak 
        title: Early prediction of human intent
        additional_links:
          - title: scholar
            icon: fab fa-google fa-spin
            url: https://asmedigitalcollection.asme.org/computingengineering/article/24/5/051004/1192601
        description: | 
          - Collected arm motion data in a human-robot collaboration experiment, <p style="color:#ff69b4;">Research interests</p>
          and built Transformer and Bi-LSTM models in TensorFlow to classify human intents.
          - Evaluated model performance by incrementally inputting data lengths from 20% 
          to 100% in 20% intervals, visualizing the results with boxplots and heatmaps.
          - Converted motion data into Euclidean distance features for a Hidden Markov Model (HMM) and
          an Autoregressive HMM to identify intent state transitions from uncertain to certain.
          - Achieved the early prediction goal by predicting intent before state transitions, 
          resulting in a 2% improvement for the Transformer model and a 6% increase for the Bi-LSTM model.
       
          
  - title: Awards
    layout: text
    content: |
      - Florida AWMA Scholarship, Florida Section of the Air and Waste Management Association, 2023
      
  - title: A Little More About Me
    layout: text
    content: | 
       - Florida AWMA Scholarship, Florida Section of the Air and Waste Management Association, 2023
  # - title: Projects
  #   layout: list
  #   content:
  #     - layout: left
  #       title: Early prediction of human intent
  #       caption: completed in 2023
  #       icon: fab fa-github
  #       url: https://asmedigitalcollection.asme.org/computingengineering/article/24/5/051004/1192601
  #       description: | 
  #         - Built Transformer and Bi-LSTM models for human motion intention classification, introducing a hidden Markov model for early prediction 
  #         that achieved a 2% accuracy increase for the Transformer and a 6% increase for the Bi-LSTM .
  # - title: Education
  #   layout: list
  #   content:
  #     - layout: top-left
  #       title: University of Florida
  #       sub_title: PhD in Environmental Engineering
  #       caption: 2021 - 2025
  #       quote: >
  #         Short institution or course description (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description of qualification
  #     - layout: top-left
  #       title: University of Michigan, Ann Arbor
  #       sub_title: MS in Environmental Engineering
  #       caption: 2019 - 2021
  #       quote: >
  #         Short institution or course description (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description of qualification
  #     - layout: top-left
  #       title: University of Michigan, Ann Arbor
  #       sub_title: MS in Environmental Engineering
  #       caption: 2019 - 2021
  #       quote: >
  #         Short institution or course description (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description of qualification


  #     Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
